name: ruang_karya
description: Aplikasi manajemen UKM Seni + Kreativitas

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.3.0

  get: ^4.6.6

  flutter_dotenv: ^5.1.0

  get_storage: ^2.1.1

  image_picker: ^1.0.7

  table_calendar: ^3.1.0

  cached_network_image: ^3.3.1

  fl_chart: ^0.67.0

  shimmer: ^3.0.0

  url_launcher: ^6.3.0

  flutter_native_splash: ^2.4.0

  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_mark.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#F6F7FB" # background soft putih abu (clean)
  image: assets/images/logo_mark.png

  android: true
  ios: false
  web: true

  fullscreen: true

  android_12:
    color: "#F6F7FB"
    image: assets/images/logo_mark.png
    icon_background_color: "#F6F7FB"


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700